# Generated by Django 5.1.4 on 2026-04-20 13:06

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Короткий опис')),
                ('body', models.TextField(blank=True, verbose_name='Повний текст')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Зображення')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубліковано')),
                ('order', models.IntegerField(default=0, verbose_name='Ручний порядок')),
            ],
            options={
                'verbose_name': 'Новина',
                'verbose_name_plural': 'Новини',
                'ordering': ('-published_at', '-id'),
                'indexes': [models.Index(fields=['-published_at'], name='news_articl_publish_62720b_idx'), models.Index(fields=['is_published'], name='news_articl_is_publ_0702a7_idx')],
            },
        ),
    ]
