# Generated by Django 5.1.4 on 2026-04-27 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='joomla_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Joomla ID'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Якщо порожньо — використовується поле Заголовок', max_length=255, verbose_name='SEO заголовок (title)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=400, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(blank=True, max_length=500, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joomla_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Joomla ID')),
                ('alias', models.SlugField(allow_unicode=True, max_length=400, unique=True, verbose_name='Alias')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('path', models.CharField(blank=True, help_text='Наприклад: materialy або pro-fpu/istoriya', max_length=400, verbose_name='URL-шлях')),
                ('meta_description', models.CharField(blank=True, max_length=1024, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=1024, verbose_name='Meta keywords')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ('path', 'title'),
                'indexes': [models.Index(fields=['path'], name='news_catego_path_112b14_idx'), models.Index(fields=['alias'], name='news_catego_alias_a44a31_idx')],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='Категорія'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['joomla_id'], name='news_articl_joomla__e2e338_idx'),
        ),
    ]
