# Generated by Django 6.0.1 on 2026-04-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_joomla_id_article_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='local_image',
            field=models.CharField(blank=True, help_text='Відносний шлях у media/joomla_images/, напр. images/foo.webp', max_length=500, verbose_name='Локальне зображення'),
        ),
    ]
