# Generated by Django 5.1.4 on 2026-04-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_key', models.CharField(choices=[('shield', 'Щит (захист прав)'), ('hard_hat', 'Каска (безпека праці)'), ('dialog', 'Діалог'), ('heart', 'Серце (допомога)')], default='shield', max_length=32, verbose_name='Іконка')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Опис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Пріоритет',
                'verbose_name_plural': 'Пріоритети',
                'ordering': ('order', 'id'),
            },
        ),
    ]
