# Generated by Django 5.1.4 on 2026-05-01 07:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(choices=[('sectoral', 'Всеукраїнська галузева'), ('regional', "Територіальне об'єднання")], default='sectoral', max_length=12, verbose_name='Тип')),
                ('name', models.CharField(max_length=500, verbose_name='Назва')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=300, unique=True, verbose_name='Slug')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регіон')),
                ('website_url', models.URLField(blank=True, verbose_name='Сайт')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Членська організація',
                'verbose_name_plural': 'Членські організації',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Федерація профспілок України', max_length=120, verbose_name='Назва сайту')),
                ('tagline', models.CharField(blank=True, max_length=240, verbose_name='Слоган')),
                ('contact_phone', models.CharField(blank=True, default='+380 44 355-77-90', max_length=40, verbose_name='Телефон')),
                ('hotline_phone', models.CharField(blank=True, default='+380 67 199-27-26', max_length=40, verbose_name='Гаряча лінія')),
                ('contact_email', models.EmailField(blank=True, default='fpsu@fpsu.org.ua', max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, default='01024, м. Київ, майдан Незалежності, 2 (Будинок Профспілок)', max_length=300, verbose_name='Адреса')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('footer_text', models.TextField(blank=True, verbose_name='Текст футера')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
