# Generated by Django 5.1.4 on 2026-05-12 09:22

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_memberorganization_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Головна сторінка'), ('about', 'Про ФПУ'), ('contacts', 'Контакти'), ('gallery', 'Галерея'), ('documents', 'Документи'), ('spo', 'СПО')], default='home', max_length=20, verbose_name='Сторінка')),
                ('section_type', models.CharField(choices=[('hero', 'Hero-банер'), ('announce', 'Оголошення-рядок'), ('promo', 'Промо-блок'), ('cta', 'Заклик до дії')], default='hero', max_length=20, verbose_name='Тип блоку')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=600, verbose_name='Підзаголовок / опис')),
                ('body', models.TextField(blank=True, verbose_name='Повний текст')),
                ('link_text', models.CharField(blank=True, max_length=120, verbose_name='Текст кнопки')),
                ('link_url', models.CharField(blank=True, help_text='Відносний /про-фпу/ або повний https://…', max_length=500, verbose_name='URL кнопки')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фонове зображення')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Блок сторінки',
                'verbose_name_plural': 'Конструктор сторінок',
                'ordering': ('page', 'order', 'id'),
            },
        ),
    ]
