# Generated by Django 6.0.1 on 2026-05-14 12:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_pagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemOrgPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Назва')),
                ('short_name', models.CharField(blank=True, max_length=200, verbose_name='Коротка назва / абревіатура')),
                ('slug', models.SlugField(allow_unicode=True, max_length=400, unique=True, verbose_name='Slug')),
                ('org_type', models.CharField(choices=[('sectoral', 'Всеукраїнська галузева'), ('regional', "Територіальне об'єднання")], default='sectoral', max_length=12, verbose_name='Тип')),
                ('region', models.CharField(blank=True, help_text="Для територіальних об'єднань", max_length=100, verbose_name='Регіон')),
                ('description', models.TextField(blank=True, verbose_name='Опис (повний текст)')),
                ('address', models.CharField(blank=True, max_length=400, verbose_name='Адреса')),
                ('phone', models.CharField(blank=True, max_length=150, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рік заснування')),
                ('website_url', models.URLField(blank=True, verbose_name='Власний сайт організації')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Логотип')),
                ('source_url', models.URLField(blank=True, help_text='Оригінальна URL-адреса на старому сайті', max_length=800, verbose_name='Джерело fpsu.org.ua')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікована')),
            ],
            options={
                'verbose_name': 'Сторінка членської організації',
                'verbose_name_plural': 'Сторінки членських організацій',
                'ordering': ('org_type', 'title'),
                'indexes': [models.Index(fields=['org_type', 'is_published'], name='core_memorg_org_typ_3554ca_idx'), models.Index(fields=['slug'], name='core_memorg_slug_d77160_idx')],
            },
        ),
    ]
