# Generated by Django 6.0.1 on 2026-05-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mem_org_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='write_us_label',
            field=models.CharField(blank=True, default='Написати нам', help_text='Текст CTA-кнопки у шапці сайту. Залиште порожнім, щоб приховати кнопку.', max_length=60, verbose_name='Кнопка «Написати нам» — текст'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='write_us_url',
            field=models.CharField(blank=True, default='/contacts/', help_text='URL або mailto:, напр. /contacts/ або mailto:fpsu@fpsu.org.ua', max_length=300, verbose_name='Кнопка «Написати нам» — посилання'),
        ),
    ]
