# Generated by Django 5.1.4 on 2026-05-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категорія документів',
                'verbose_name_plural': 'Категорії документів',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Назва')),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/', verbose_name='Файл')),
                ('file_url', models.URLField(blank=True, help_text='Якщо документ зберігається за зовнішнім URL', verbose_name='Зовнішнє URL')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC/DOCX'), ('xls', 'XLS/XLSX'), ('other', 'Інше')], default='pdf', max_length=8, verbose_name='Тип файлу')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Дата публікації')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікований')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentcategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
                'ordering': ('-published_at', '-created_at', 'order'),
                'indexes': [models.Index(fields=['category', 'is_published'], name='documents_d_categor_0b4b84_idx'), models.Index(fields=['-published_at'], name='documents_d_publish_34515d_idx')],
            },
        ),
    ]
