# Generated by Django 5.1.4 on 2026-05-01 07:44

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joomla_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Joomla ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('slug', models.SlugField(allow_unicode=True, max_length=300, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Дата заходу')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Обкладинка')),
                ('cover_local', models.CharField(blank=True, help_text='Шлях у media/joomla_images/', max_length=500, verbose_name='Локальна обкладинка')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікований')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбоми',
                'ordering': ('-event_date', '-created_at'),
                'indexes': [models.Index(fields=['slug'], name='gallery_gal_slug_7a3c1f_idx'), models.Index(fields=['is_published', '-event_date'], name='gallery_gal_is_publ_e787fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joomla_id', models.IntegerField(blank=True, null=True, verbose_name='Joomla ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Фото')),
                ('image_local', models.CharField(blank=True, help_text='Відносний шлях у media/joomla_images/', max_length=500, verbose_name='Локальний шлях')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Підпис')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікована')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.galleryalbum', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографії',
                'ordering': ('order', 'id'),
                'indexes': [models.Index(fields=['album', 'is_published', 'order'], name='gallery_gal_album_i_79aa59_idx')],
            },
        ),
    ]
