# Generated by Django 5.1.4 on 2026-04-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(help_text='Наприклад: /pro-fpu/istoriya-fpu або /276-cherhovyi-den.html', max_length=500, unique=True, verbose_name='URL-шлях')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('meta_title', models.CharField(blank=True, help_text='Якщо порожньо — використовується Заголовок', max_length=255, verbose_name='SEO заголовок')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Meta keywords')),
                ('body', models.TextField(blank=True, verbose_name='Вміст сторінки')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікована')),
                ('joomla_id', models.IntegerField(blank=True, null=True, verbose_name='Joomla menu/article ID')),
                ('joomla_type', models.CharField(blank=True, help_text='menu | article', max_length=50, verbose_name='Тип Joomla')),
            ],
            options={
                'verbose_name': 'Статична сторінка',
                'verbose_name_plural': 'Статичні сторінки',
                'ordering': ('url_path',),
                'indexes': [models.Index(fields=['url_path'], name='pages_stati_url_pat_006d9d_idx')],
            },
        ),
    ]
